### PR TITLE
Add valueFileSecrets example to Redis release

### PR DESCRIPTION
**Pull request by stefanprodan**
Fix https://github.com/weaveworks/flux/issues/1617

### CODE REVIEW

**Comment by stefanprodan** [comment]
@squaremo can you please review this? 

Thanks

**Comment by squaremo** [comment]
If we're using an unexcrypted secret, and just suggesting people use sealed secrets, do we need the sealed-secret chart release?

**Comment by stefanprodan** [comment]
I've put the sealed-secret chart release in this repo so I can link to it when people ask about secrets. I can remove it or use the `ignore` annotation, we don't have an example for that anyway.

**Comment by squaremo** [comment]
Your gitops-helm repo has the more complete example (which you can point to) -- I think you can remove it here.

**Comment by stefanprodan** [comment]
Done

**Review by squaremo — APPROVED** [review]
Cool, good to show this feature -- thanks Stefan

**Pull request merged**
